# Generated by Django 3.2.12 on 2022-10-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20221017_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='abn',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='abp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='an',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='ap',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='bn',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='bp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='on',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='op',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
